const products = [
  {
    id: 1,
    image: [
      "images/fgo/Fate Grand Order - Vol.5 Plush Keychain SEGA x Sanrio/FateGrandOorder Vol5 Plush Keychain Sega x Sanrio.jpg",
    ],
    name: "Fate/Grand Order - Vol.5 Plush Keychain SEGA x Sanrio",
    series: "Fate/Grand Order",
    character: "test",
    material: "test",
    productType: "Plush Keychain",
    manufacturer: "SEGA x Sanrio",
    dimensions: "N/A",
    price: 24.99,
    instock: 5,
    anime: "fate-grand-order",
  },
  {
    id: 2,
    image: [
      "images/onepiece/Yamato ONE PIECE Portrait.Of.Pirates WA-MAXIMUM Figure MegaHouse/Yamato ONE PIECE PortraitOfPirates WA-MAXIMUM Figure MegaHouse.jpg",
      "images/onepiece/Yamato ONE PIECE Portrait.Of.Pirates WA-MAXIMUM Figure MegaHouse/Yamato ONE PIECE PortraitOfPirates WA-MAXIMUM Figure MegaHouse (1).jpg",
      "images/onepiece/Yamato ONE PIECE Portrait.Of.Pirates WA-MAXIMUM Figure MegaHouse/Yamato ONE PIECE PortraitOfPirates WA-MAXIMUM Figure MegaHouse (2).jpg",
      "images/onepiece/Yamato ONE PIECE Portrait.Of.Pirates WA-MAXIMUM Figure MegaHouse/Yamato ONE PIECE PortraitOfPirates WA-MAXIMUM Figure MegaHouse (3).jpg",
      "images/onepiece/Yamato ONE PIECE Portrait.Of.Pirates WA-MAXIMUM Figure MegaHouse/Yamato ONE PIECE PortraitOfPirates WA-MAXIMUM Figure MegaHouse (4).jpg",
      "images/onepiece/Yamato ONE PIECE Portrait.Of.Pirates WA-MAXIMUM Figure MegaHouse/Yamato ONE PIECE PortraitOfPirates WA-MAXIMUM Figure MegaHouse (5).jpg",
      "images/onepiece/Yamato ONE PIECE Portrait.Of.Pirates WA-MAXIMUM Figure MegaHouse/Yamato ONE PIECE PortraitOfPirates WA-MAXIMUM Figure MegaHouse (6).jpg",
      "images/onepiece/Yamato ONE PIECE Portrait.Of.Pirates WA-MAXIMUM Figure MegaHouse/Yamato ONE PIECE PortraitOfPirates WA-MAXIMUM Figure MegaHouse (7).jpg",
      "images/onepiece/Yamato ONE PIECE Portrait.Of.Pirates WA-MAXIMUM Figure MegaHouse/Yamato ONE PIECE PortraitOfPirates WA-MAXIMUM Figure MegaHouse (8).jpg",
    ],
    name: "One Piece - Yamato ONE PIECE Portrait.Of.Pirates WA-MAXIMUM Figure MegaHouse",
    series: "One Piece",
    character: "test",
    material: "test",
    productType: "Acrylic Stand",
    manufacturer: "test",
    dimensions: "test",
    price: 18.99,
    instock: 5,
    anime: "one-piece",
  },
  {
    id: 3,
    image: [
      "images/hatsune-miku/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu.jpg",
      "images/hatsune-miku/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu (1).jpg",
      "images/hatsune-miku/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu (2).jpg",
      "images/hatsune-miku/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu (3).jpg",
      "images/hatsune-miku/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu (4).jpg",
      "images/hatsune-miku/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu (5).jpg",
      "images/hatsune-miku/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu (6).jpg",
      "images/hatsune-miku/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu (7).jpg",
      "images/hatsune-miku/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu (8).jpg",
      "images/hatsune-miku/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu (9).jpg",
      "images/hatsune-miku/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu (10).jpg",
      "images/hatsune-miku/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu (11).jpg",
      "images/hatsune-miku/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu/Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu (12).jpg",
    ],
    name: "Hatsune Miku - Hatsune Miku White Acghot 39 T-shirt Moeyu",
    series: "Hatsune Miku",
    character: "test",
    material: "test",
    productType: "Clothing",
    manufacturer: "test",
    dimensions: "test",
    price: 21.99,
    instock: 5,
    anime: "hatsune-miku",
  },
  {
    id: 4,
    image: "",
    name: "MY HERO ACADEMIA - Katsuki Bakugo (THE AMAZING HEROES vol.14) Prize Figure Banpresto",
    series: "My Hero Academia",
    character: "test",
    material: "test",
    productType: "Clothing",
    manufacturer: "test",
    dimensions: "test",
    price: 30.99,
    instock: 5,
    anime: "my-hero-academia",
  },
  {
    id: 5,
    image: "",
    name: "The Quintessential Quintuplets - Miku Nakano",
    series: "The Quintessential Quintuplets",
    character: "test",
    material: "test",
    productType: "Plushies",
    manufacturer: "test",
    dimensions: "test",
    price: 10.99,
    instock: 5,
    anime: "the-quintessential-quintuplets",
  },
  {
    id: 6,
    image: "",
    name: "Demon Slayer - Tanjiro Kamado (2nd re-run) Nendoroid",
    series: "Demon Slayer",
    character: "test",
    material: "test",
    productType: "Accessories",
    manufacturer: "test",
    dimensions: "test",
    price: 15.99,
    instock: 5,
    anime: "demon-slayer",
  },
  {
    id: 7,
    image: "",
    name: "Sword Art Online (Alicization) - Yuuki Asuna Keychain",
    series: "Sword Art Online (Alicization)",
    character: "test",
    material: "test",
    productType: "Other",
    manufacturer: "test",
    dimensions: "test",
    price: 7.99,
    instock: 5,
    anime: "sword-art-online",
  },
  {
    id: 8,
    image: "",
    name: "Demon Slayer - Tanjiro Kamado (2nd re-run) Nendoroid",
    series: "Demon Slayer",
    character: "test",
    material: "test",
    productType: "Accessories",
    manufacturer: "test",
    dimensions: "test",
    price: 15.99,
    instock: 5,
    anime: "demon-slayer",
  },
  {
    id: 9,
    image: "",
    name: "Demon Slayer - Tanjiro Kamado (2nd re-run) Nendoroid",
    series: "Demon Slayer",
    character: "test",
    material: "test",
    productType: "Accessories",
    manufacturer: "test",
    dimensions: "test",
    price: 15.99,
    instock: 5,
    anime: "demon-slayer",
  },
  {
    id: 10,
    image: [
      "images/hatsune-miku/Hatsune Miku - Hatsune Miku Falling Series Mini Figure Blind Box Moeyu/Hatsune Miku - Hatsune Miku Falling Series Mini Figure Blind Box Moeyu.jpg",
    ],
    name: "Hatsune Miku - Hatsune Miku Falling Series Mini Figure Blind Box Moeyu",
    series: "Hatsune Miku",
    material: "PVC & ABS",
    productType: "Blind Box",
    manufacturer: "Moeyu",
    dimensions: "Approximately 6-10cm ",
    price: 18.0,
    instock: 5,
    anime: "hatsune-miku",
  },
];
